## This configuration was generated by terraform-provider-oci

data oci_identity_availability_domain export_clNq-US-ASHBURN-AD-1 {
  compartment_id = var.compartment_ocid
  ad_number      = "1"
}
data oci_identity_availability_domain export_clNq-US-ASHBURN-AD-2 {
  compartment_id = var.compartment_ocid
  ad_number      = "2"
}
data oci_identity_availability_domain export_clNq-US-ASHBURN-AD-3 {
  compartment_id = var.compartment_ocid
  ad_number      = "3"
}
resource oci_file_storage_file_system export_kentnfsp01 {
  availability_domain = var.availability_domain--clNq-US-ASHBURN-AD-2
  compartment_id      = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/hankwojteczko@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2022-12-19T21:01:41.445Z"
  }
  display_name = "kentnfsp01"
  freeform_tags = {
  }
  kms_key_id = ""
  #source_snapshot_id = <<Optional value not found in discovery>>
}

resource oci_file_storage_mount_target export_kentnfsp01_mt {
  availability_domain = var.availability_domain--clNq-US-ASHBURN-AD-2
  compartment_id      = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/hankwojteczko@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2022-12-19T21:01:44.957Z"
  }
  display_name = "kentnfsp01_mt"
  freeform_tags = {
  }
  #hostname_label = <<Optional value not found in discovery>>
  ip_address = "172.16.0.173"
  nsg_ids = [
  ]
  subnet_id = oci_core_subnet.export_dbs_sub.id
}

resource oci_file_storage_file_system export_kentnfst01 {
  availability_domain = var.availability_domain--clNq-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/hankwojteczko@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2022-12-19T21:02:49.586Z"
  }
  display_name = "kentnfst01"
  freeform_tags = {
  }
  kms_key_id = ""
  #source_snapshot_id = <<Optional value not found in discovery>>
}

resource oci_file_storage_mount_target export_kentnfst01_mt {
  availability_domain = var.availability_domain--clNq-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/hankwojteczko@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2022-12-19T21:02:53.167Z"
  }
  display_name = "kentnfst01_mt"
  freeform_tags = {
  }
  #hostname_label = <<Optional value not found in discovery>>
  ip_address = "172.16.0.49"
  nsg_ids = [
  ]
  subnet_id = oci_core_subnet.export_dbs_sub.id
}

