# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
  - task: UsePythonVersion@0
    displayName: 'Install Python'
    inputs:
      versionSpec: '3.10.9'

  - task: Bash@3
    displayName: "install oci api"
    inputs:
      targetType: inline
      script: /bin/pip install oci==2.88.2

  # - task: Bash@3
  #   displayName: "prepare to install oci cli"
  #   inputs:
  #    targetType: inline
  #    script: /bin/curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh > install.sh

  # - task: Bash@3
  #   displayName: "set oci cli script to 750"
  #   inputs:
  #     targetType: inline
  #     script: /bin/chmod 750 install.sh
  
  - task: Bash@3
    displayName: "pwd"
    inputs:
      targetType: inline
      script: /bin/pwd
     
  - task: Bash@3
    displayName: 'set install oci script'
    inputs:
      targetType: inline
      script: /bin/chmod 500 setup.sh

  - task: Bash@3
    displayName: 'run the oci setup script'
    inputs:
      targetType: inline
      script: /home/vsts/work/1/s/setup.sh