## This configuration was generated by terraform-provider-oci

resource oci_core_drg export_dbs_drg {
  compartment_id = var.compartment_ocid
  defined_tags = {
  }
  display_name = "dbs_drg"
  freeform_tags = {
    "Environment"       = "Production"
    "Platform"          = "Managed by Terraform"
    "accounting_code"   = "ITS"
  }
}

resource oci_core_internet_gateway export_EM-Internet-Gateway---EMDBSubnet-172-16-0-0-24- {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/hankwojteczko@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2021-02-24T16:16:42.289Z"
  }
  display_name = "EM Internet Gateway - EMDBSubnet (172.16.0.0/24)"
  enabled      = "true"
  freeform_tags = {
    "Environment" = "Production"
    "Platform"    = "Managed by Terraform"
  }
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_dbs_vcn.id
}

resource oci_core_drg_attachment export_dbs_drg_attachment {
  #defined_tags = <<Optional value not found in discovery>>
  display_name = "dbs_drg_attachment"
  drg_id       = oci_core_drg.export_dbs_drg.id
  #drg_route_table_id = <<Optional value not found in discovery>>
  #export_drg_route_distribution_id = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  #remove_export_drg_route_distribution_trigger = <<Optional value not found in discovery>>
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_dbs_vcn.id
}

resource oci_core_network_security_group export_EM-Security-Group---EMDBSubnet-172-16-0-0-24- {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/hankwojteczko@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2021-02-24T16:16:42.281Z"
  }
  display_name = "EM Security Group - EMDBSubnet (172.16.0.0/24)"
  freeform_tags = {
    "Environment" = "Production"
    "Platform"    = "Managed by Terraform"
  }
  vcn_id = oci_core_vcn.export_dbs_vcn.id
}

resource oci_core_subnet export_dbs_sub {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "172.16.0.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "edwinyoung@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2020-05-27T21:27:18.766Z"
  }
  dhcp_options_id = oci_core_vcn.export_dbs_vcn.default_dhcp_options_id
  display_name    = "dbs_sub"
  dns_label       = "dbssub"
  freeform_tags = {
    "Environment" = "Production"
    "Platform"    = "Managed by Terraform"
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "true"
  prohibit_public_ip_on_vnic = "true"
  route_table_id             = oci_core_route_table.export_dbs_rtb.id
  security_list_ids = [
    oci_core_security_list.export_dbs_sec.id,
  ]
  vcn_id = oci_core_vcn.export_dbs_vcn.id
}

resource oci_core_vcn export_dbs_vcn {
  #byoipv6cidr_details = <<Optional value not found in discovery>>
  #cidr_block = <<Optional value not found in discovery>>
  cidr_blocks = [
    "172.16.0.0/24",
  ]
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "edwinyoung@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2020-05-27T21:22:28.478Z"
  }
  display_name = "dbs_vcn"
  dns_label    = "dbsvcn"
  freeform_tags = {
    "Environment" = "Production"
    "Platform"    = "Managed by Terraform"
  }
  ipv6private_cidr_blocks = [
  ]
  #is_ipv6enabled = <<Optional value not found in discovery>>
  #is_oracle_gua_allocation_enabled = <<Optional value not found in discovery>>
}

resource oci_core_remote_peering_connection export_dbs_drg_rpc {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/hankwojteczko@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2021-09-08T17:27:54.748Z"
  }
  display_name = "dbs_drg_rpc"
  drg_id       = oci_core_drg.export_dbs_drg.id
  freeform_tags = {
    "Environment" = "Production"
    "Platform"    = "Managed by Terraform"
  }
  peer_id          = "ocid1.remotepeeringconnection.oc1.phx.aaaaaaaa33f5yuujqygqppvflovjhsqvjsp2ihwqbohuhcywhlzzmwmjtara"
  peer_region_name = "us-phoenix-1"
}

resource oci_core_network_security_group_security_rule export_EM-Security-Group---EMDBSubnet-172-16-0-0-24-_network_security_group_security_rule_1 {
  description = "EM Local Database - 1521"
  #destination = <<Optional value not found in discovery>>
  destination_type          = ""
  direction                 = "INGRESS"
  network_security_group_id = oci_core_network_security_group.export_EM-Security-Group---EMDBSubnet-172-16-0-0-24-.id
  protocol                  = "6"
  source                    = "172.16.0.0/24"
  source_type               = "CIDR_BLOCK"
  stateless                 = "false"
  tcp_options {
    destination_port_range {
      max = "1521"
      min = "1521"
    }
    #source_port_range = <<Optional value not found in discovery>>
  }
}

resource oci_core_network_security_group_security_rule export_EM-Security-Group---EMDBSubnet-172-16-0-0-24-_network_security_group_security_rule_2 {
  description = "BI Publisher Managed Server - 9801"
  #destination = <<Optional value not found in discovery>>
  destination_type          = ""
  direction                 = "INGRESS"
  network_security_group_id = oci_core_network_security_group.export_EM-Security-Group---EMDBSubnet-172-16-0-0-24-.id
  protocol                  = "6"
  source                    = "172.16.0.0/24"
  source_type               = "CIDR_BLOCK"
  stateless                 = "false"
  tcp_options {
    destination_port_range {
      max = "9801"
      min = "9801"
    }
    #source_port_range = <<Optional value not found in discovery>>
  }
}

resource oci_core_network_security_group_security_rule export_EM-Security-Group---EMDBSubnet-172-16-0-0-24-_network_security_group_security_rule_3 {
  description = "EM Admin Server - 7101"
  #destination = <<Optional value not found in discovery>>
  destination_type          = ""
  direction                 = "INGRESS"
  network_security_group_id = oci_core_network_security_group.export_EM-Security-Group---EMDBSubnet-172-16-0-0-24-.id
  protocol                  = "6"
  source                    = "172.16.0.0/24"
  source_type               = "CIDR_BLOCK"
  stateless                 = "false"
  tcp_options {
    destination_port_range {
      max = "7101"
      min = "7101"
    }
    #source_port_range = <<Optional value not found in discovery>>
  }
}

resource oci_core_network_security_group_security_rule export_EM-Security-Group---EMDBSubnet-172-16-0-0-24-_network_security_group_security_rule_4 {
  description = "EM Upload - 4900"
  #destination = <<Optional value not found in discovery>>
  destination_type          = ""
  direction                 = "INGRESS"
  network_security_group_id = oci_core_network_security_group.export_EM-Security-Group---EMDBSubnet-172-16-0-0-24-.id
  protocol                  = "6"
  source                    = "172.16.0.0/24"
  source_type               = "CIDR_BLOCK"
  stateless                 = "false"
  tcp_options {
    destination_port_range {
      max = "4900"
      min = "4900"
    }
    #source_port_range = <<Optional value not found in discovery>>
  }
}

resource oci_core_network_security_group_security_rule export_EM-Security-Group---EMDBSubnet-172-16-0-0-24-_network_security_group_security_rule_5 {
  description = "BI Publisher Console - 9899"
  #destination = <<Optional value not found in discovery>>
  destination_type          = ""
  direction                 = "INGRESS"
  network_security_group_id = oci_core_network_security_group.export_EM-Security-Group---EMDBSubnet-172-16-0-0-24-.id
  protocol                  = "6"
  source                    = "172.16.0.0/24"
  source_type               = "CIDR_BLOCK"
  stateless                 = "false"
  tcp_options {
    destination_port_range {
      max = "9899"
      min = "9899"
    }
    #source_port_range = <<Optional value not found in discovery>>
  }
}

resource oci_core_network_security_group_security_rule export_EM-Security-Group---EMDBSubnet-172-16-0-0-24-_network_security_group_security_rule_6 {
  description = "EM Agent - 3872"
  #destination = <<Optional value not found in discovery>>
  destination_type          = ""
  direction                 = "INGRESS"
  network_security_group_id = oci_core_network_security_group.export_EM-Security-Group---EMDBSubnet-172-16-0-0-24-.id
  protocol                  = "6"
  source                    = "172.16.0.0/24"
  source_type               = "CIDR_BLOCK"
  stateless                 = "false"
  tcp_options {
    destination_port_range {
      max = "3872"
      min = "3872"
    }
    #source_port_range = <<Optional value not found in discovery>>
  }
}

resource oci_core_network_security_group_security_rule export_EM-Security-Group---EMDBSubnet-172-16-0-0-24-_network_security_group_security_rule_7 {
  description = "EM Managed Server/JVMD - 7301"
  #destination = <<Optional value not found in discovery>>
  destination_type          = ""
  direction                 = "INGRESS"
  network_security_group_id = oci_core_network_security_group.export_EM-Security-Group---EMDBSubnet-172-16-0-0-24-.id
  protocol                  = "6"
  source                    = "172.16.0.0/24"
  source_type               = "CIDR_BLOCK"
  stateless                 = "false"
  tcp_options {
    destination_port_range {
      max = "7301"
      min = "7301"
    }
    #source_port_range = <<Optional value not found in discovery>>
  }
}

resource oci_core_network_security_group_security_rule export_EM-Security-Group---EMDBSubnet-172-16-0-0-24-_network_security_group_security_rule_8 {
  description = "EM Console - 7799"
  #destination = <<Optional value not found in discovery>>
  destination_type          = ""
  direction                 = "INGRESS"
  network_security_group_id = oci_core_network_security_group.export_EM-Security-Group---EMDBSubnet-172-16-0-0-24-.id
  protocol                  = "6"
  source                    = "172.16.0.0/24"
  source_type               = "CIDR_BLOCK"
  stateless                 = "false"
  tcp_options {
    destination_port_range {
      max = "7799"
      min = "7799"
    }
    #source_port_range = <<Optional value not found in discovery>>
  }
}

resource oci_core_network_security_group_security_rule export_EM-Security-Group---EMDBSubnet-172-16-0-0-24-_network_security_group_security_rule_9 {
  description = "EM Node Manager - 7401"
  #destination = <<Optional value not found in discovery>>
  destination_type          = ""
  direction                 = "INGRESS"
  network_security_group_id = oci_core_network_security_group.export_EM-Security-Group---EMDBSubnet-172-16-0-0-24-.id
  protocol                  = "6"
  source                    = "172.16.0.0/24"
  source_type               = "CIDR_BLOCK"
  stateless                 = "false"
  tcp_options {
    destination_port_range {
      max = "7401"
      min = "7401"
    }
    #source_port_range = <<Optional value not found in discovery>>
  }
}

resource oci_core_volume_attachment export_volumeattachment20221201180308 {
  attachment_type = "paravirtualized"
  #device = <<Optional value not found in discovery>>
  display_name = "volumeattachment20221201180308"
  #encryption_in_transit_type = <<Optional value not found in discovery>>
  instance_id = oci_core_instance.export_kentemsp01_1.id
  #is_agent_auto_iscsi_login_enabled = <<Optional value not found in discovery>>
  is_pv_encryption_in_transit_enabled = "false"
  is_read_only                        = "false"
  #is_shareable = <<Optional value not found in discovery>>
  #use_chap = <<Optional value not found in discovery>>
  volume_id = oci_core_volume.export_kentesmp01_datadisk_00.id
}

resource oci_core_volume export_kentesmp01_datadisk_00 {
  availability_domain = var.availability_domain--clNq-US-ASHBURN-AD-1
  #block_volume_replicas_deletion = <<Optional value not found in discovery>>
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/hankwojteczko@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2022-12-01T18:02:35.651Z"
  }
  display_name = "kentesmp01_datadisk_00"
  freeform_tags = {
    "Environment" = "Production"
    "Platform"    = "Managed by Terraform"
  }
  is_auto_tune_enabled = "false"
  #kms_key_id = <<Optional value not found in discovery>>
  size_in_gbs = "250"
  #volume_backup_id = <<Optional value not found in discovery>>
  vpus_per_gb = "10"
}

resource oci_core_private_ip export_fss-mnt-1000000014106096 {
  defined_tags = {
  }
  display_name = "fss-mnt-1000000014106096"
  freeform_tags = {
  }
  #hostname_label = <<Optional value not found in discovery>>
  ip_address = "172.16.0.16"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.iad.abuwcljrwcgtuoje2qncpybkmq3zrxbclxylf26rptsjlnydgztqohtplw2q"
}

resource oci_core_private_ip export_ocid1-dbnode-oc1-iad-anuwcljrdugb54qagu622tj3nezkytilog4imqdgaxc7efcrpyngqkp2omfa {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/hankwojteczko@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2022-12-01T18:39:38.220Z"
  }
  display_name = "ocid1.dbnode.oc1.iad.anuwcljrdugb54qagu622tj3nezkytilog4imqdgaxc7efcrpyngqkp2omfa"
  freeform_tags = {
  }
  hostname_label = "kentdbp01"
  ip_address     = "172.16.0.43"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.iad.abuwcljrypp7zri37apxnti5m7v6pub6zwe4cosliuguw2h2svq4bhvnglsa"
}

resource oci_core_private_ip export_fss-mnt-1000000014106096_1 {
  defined_tags = {
  }
  display_name = "fss-mnt-1000000014106096"
  freeform_tags = {
  }
  #hostname_label = <<Optional value not found in discovery>>
  ip_address = "172.16.0.46"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.iad.abuwcljrbudbccggfhvs3jpvsr3k7cc7u7amhutrf3zvwgdof53ep7fzm6ga"
}

resource oci_core_private_ip export_kentjsubp01 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/hankwojteczko@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2022-12-01T17:59:49.899Z"
  }
  display_name = "kentjsubp01"
  freeform_tags = {
  }
  hostname_label = "kentjsubp01"
  ip_address     = "172.16.0.50"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.iad.abuwcljtabqnsxd3fidkeboxgkf7yh5ecuzsiqy5gxckqcbedkpf2daktoiq"
}

resource oci_core_private_ip export_fss-mnt-2000000012034293 {
  defined_tags = {
  }
  display_name = "fss-mnt-2000000012034293"
  freeform_tags = {
  }
  #hostname_label = <<Optional value not found in discovery>>
  ip_address = "172.16.0.69"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.iad.abuwcljtwr2xqvxdczovewfiwxukbxmp2tau3psj4m2gygtgw4e57dod45rq"
}

resource oci_core_private_ip export_ocid1-dbnode-oc1-iad-anuwcljtdugb54qaah2gavdffegacx3xwaxvd5kzrt6senen6oos5dkcb7za {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/hankwojteczko@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2022-12-01T18:42:05.153Z"
  }
  display_name = "ocid1.dbnode.oc1.iad.anuwcljtdugb54qaah2gavdffegacx3xwaxvd5kzrt6senen6oos5dkcb7za"
  freeform_tags = {
  }
  hostname_label = "kentdbt01"
  ip_address     = "172.16.0.118"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.iad.abuwcljt4woroagi64onhq5zkytpmlqax6xumcwdumuadushqksr7ghw2s4a"
}

resource oci_core_private_ip export_privateip20210207164051 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "fssoc1prod"
    "Oracle-Tags.CreatedOn" = "2021-02-07T16:40:51.790Z"
  }
  display_name = "privateip20210207164051"
  freeform_tags = {
    "Environment" = "Production"
    "Platform"    = "Managed by Terraform"
  }
  hostname_label = "kentfst01"
  ip_address     = "172.16.0.125"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.iad.abuwcljtvg4xat6zdjhnojru3ncucybrsoloqmgllh7ehjfdn4upcrovsdbq"
}

resource oci_core_private_ip export_privateip20210207172140 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "fssoc1prod"
    "Oracle-Tags.CreatedOn" = "2021-02-07T17:21:40.170Z"
  }
  display_name = "privateip20210207172140"
  freeform_tags = {
    "Environment" = "Production"
    "Platform"    = "Managed by Terraform"
  }
  hostname_label = "kentfst01mt"
  ip_address     = "172.16.0.126"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.iad.abuwcljrbudbccggfhvs3jpvsr3k7cc7u7amhutrf3zvwgdof53ep7fzm6ga"
}

resource oci_core_private_ip export_kentjsubt01 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/hankwojteczko@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2022-12-01T17:59:04.322Z"
  }
  display_name = "kentjsubt01"
  freeform_tags = {
  }
  hostname_label = "kentjsubt01"
  ip_address     = "172.16.0.154"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.iad.abuwcljrmp73i53ocwgsxdszy27ts5fbqn3pqy55svls6my34vtcaiwkypqq"
}

resource oci_core_private_ip export_fss-mnt-2000000012034293_1 {
  defined_tags = {
  }
  display_name = "fss-mnt-2000000012034293"
  freeform_tags = {
  }
  #hostname_label = <<Optional value not found in discovery>>
  ip_address = "172.16.0.196"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.iad.abuwcljtvg4xat6zdjhnojru3ncucybrsoloqmgllh7ehjfdn4upcrovsdbq"
}

resource oci_core_private_ip export_kentemsp01 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/hankwojteczko@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2022-12-01T18:00:37.054Z"
  }
  display_name = "kentemsp01"
  freeform_tags = {
  }
  hostname_label = "kentemsp01"
  ip_address     = "172.16.0.239"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.iad.abuwcljsdaz5qf7wl2hlou7mt4uhluziueoe5gubjezjxiwjla7w2qadhgrq"
}

resource oci_core_private_ip export_ocid1-dbnode-oc1-iad-anuwcljsdugb54qa5qx5ebugzfcst2n3qsu5qyu65f2y53lreocgsy7me43q {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/hankwojteczko@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2022-12-01T18:45:03.238Z"
  }
  display_name = "ocid1.dbnode.oc1.iad.anuwcljsdugb54qa5qx5ebugzfcst2n3qsu5qyu65f2y53lreocgsy7me43q"
  freeform_tags = {
  }
  hostname_label = "kentcatp01"
  ip_address     = "172.16.0.251"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.iad.abuwcljseq7bqa7rqgoftnnpmizczq2eq56ebd5d5tudsifucbs3ylbf5hka"
}

resource oci_core_local_peering_gateway export_DbsToBasLpg {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/hankwojteczko@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2021-04-05T20:53:37.998Z"
  }
  display_name = "DbsToBasLpg"
  freeform_tags = {
    "Environment" = "Production"
    "Platform"    = "Managed by Terraform"
  }
  peer_id = "ocid1.localpeeringgateway.oc1.iad.aaaaaaaajwzdex4dknzrf5orkoza35xy3ep4a7akdvhdhkczes2fautn7gxq"
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_dbs_vcn.id
}

resource oci_core_local_peering_gateway export_DbsToWebLpg {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "edwinyoung@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2020-05-27T21:40:41.198Z"
  }
  display_name = "DbsToWebLpg"
  freeform_tags = {
    "Environment" = "Production"
    "Platform"    = "Managed by Terraform"
  }
  peer_id = "ocid1.localpeeringgateway.oc1.iad.aaaaaaaadqlbcaehe3fmgg645f5xxkuxadpsszpk34wzefxksl5ivf2nqqba"
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_dbs_vcn.id
}

resource oci_core_local_peering_gateway export_DbsToTstLpg {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/hankwojteczko@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2020-10-09T21:59:19.301Z"
  }
  display_name = "DbsToTstLpg"
  freeform_tags = {
    "Environment" = "Production"
    "Platform"    = "Managed by Terraform"
  }
  peer_id = "ocid1.localpeeringgateway.oc1.iad.aaaaaaaaa6w45gcxtxdb5mqdgbdxp2f4du2oej3wfoqly4fjoxkirwf6tgeq"
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_dbs_vcn.id
}

resource oci_core_local_peering_gateway export_DbsToAutoLpg {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "edwinyoung@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2020-05-27T21:38:06.927Z"
  }
  display_name = "DbsToAutoLpg"
  freeform_tags = {
    "Environment" = "Production"
    "Platform"    = "Managed by Terraform"
  }
  peer_id = "ocid1.localpeeringgateway.oc1.iad.aaaaaaaazoknzqb6zs7wlkdmuaqjkk3w3q6adiszvjdz3uex35a6z7ktix7q"
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_dbs_vcn.id
}

resource oci_core_local_peering_gateway export_DbsToOemLpg {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "hankwojteczko@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2021-03-30T18:29:19.773Z"
  }
  display_name = "DbsToOemLpg"
  freeform_tags = {
    "Environment" = "Production"
    "Platform"    = "Managed by Terraform"
  }
  peer_id = "ocid1.localpeeringgateway.oc1.iad.aaaaaaaav4hkkjhe3x3bookbeq3c3qe2qdx4wjknk3jf7poczuv3pt7zsefa"
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_dbs_vcn.id
}

resource oci_core_local_peering_gateway export_DbsToVpnLpg {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "edwinyoung@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2020-05-27T21:40:03.540Z"
  }
  display_name = "DbsToVpnLpg"
  freeform_tags = {
    "Environment" = "Production"
    "Platform"    = "Managed by Terraform"
  }
  peer_id = "ocid1.localpeeringgateway.oc1.iad.aaaaaaaa2frre6ev44hu67th3nobghf5254fus2e5cplt7fby44xnqcj77zq"
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_dbs_vcn.id
}

resource oci_core_local_peering_gateway export_DmzToWebLpg {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/hankwojteczko@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2020-06-01T14:42:49.171Z"
  }
  display_name = "DmzToWebLpg"
  freeform_tags = {
    "Environment" = "Production"
    "Platform"    = "Managed by Terraform"
  }
  #peer_id = <<Optional value not found in discovery>>
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_dbs_vcn.id
}

resource oci_core_local_peering_gateway export_DbsToDmzLpg {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/hankwojteczko@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2020-06-01T14:51:04.457Z"
  }
  display_name = "DbsToDmzLpg"
  freeform_tags = {
    "Environment" = "Production"
    "Platform"    = "Managed by Terraform"
  }
  peer_id = "ocid1.localpeeringgateway.oc1.iad.aaaaaaaa5p5w4zmmpyblv6nts4zwqoj26bemscxuqz342yut7hw7wh2o6ukq"
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_dbs_vcn.id
}

resource oci_core_service_gateway export_EM-Service-Gateway---EMDBSubnet-172-16-0-0-24- {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/hankwojteczko@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2021-02-24T16:16:42.293Z"
  }
  display_name = "EM Service Gateway - EMDBSubnet (172.16.0.0/24)"
  freeform_tags = {
    "Environment" = "Production"
    "Platform"    = "Managed by Terraform"
  }
  #route_table_id = <<Optional value not found in discovery>>
  services {
    service_id = "ocid1.service.oc1.iad.aaaaaaaam4zfmy2rjue6fmglumm3czgisxzrnvrwqeodtztg7hwa272mlfna"
  }
  vcn_id = oci_core_vcn.export_dbs_vcn.id
}

resource oci_core_default_dhcp_options export_Default-DHCP-Options-for-dbs_vcn {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "edwinyoung@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2020-05-27T21:22:28.478Z"
  }
  display_name     = "Default DHCP Options for dbs_vcn"
  domain_name_type = "CUSTOM_DOMAIN"
  freeform_tags = {
    "Environment" = "Production"
    "Platform"    = "Managed by Terraform"
  }
  manage_default_resource_id = oci_core_vcn.export_dbs_vcn.default_dhcp_options_id
  options {
    custom_dns_servers = [
    ]
    #search_domain_names = <<Optional value not found in discovery>>
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
  options {
    #custom_dns_servers = <<Optional value not found in discovery>>
    search_domain_names = [
      "dbsvcn.oraclevcn.com",
    ]
    #server_type = <<Optional value not found in discovery>>
    type = "SearchDomain"
  }
}

resource oci_core_nat_gateway export_dbs_ngw {
  block_traffic  = "false"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/hankwojteczko@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2022-07-28T19:42:42.315Z"
  }
  display_name = "dbs_ngw"
  freeform_tags = {
    "Environment" = "Production"
    "Platform"    = "Managed by Terraform"
  }
  public_ip_id = "ocid1.publicip.oc1.iad.aaaaaaaanexrkj3xbeel3747u66jp4exmfd72jt5hls57qf3umj244i7k4oa"
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_dbs_vcn.id
}

resource oci_core_route_table export_dbs_rtb {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "edwinyoung@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2020-05-27T23:09:45.911Z"
  }
  display_name = "dbs_rtb"
  freeform_tags = {
    "Environment" = "Production"
    "Platform"    = "Managed by Terraform"
  }
  route_rules {
    description       = "Route to oem_vcn"
    destination       = "172.16.8.0/24"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_local_peering_gateway.export_DbsToOemLpg.id
    #route_type = <<Optional value not found in discovery>>
  }
  route_rules {
    description       = "route to web_vcn"
    destination       = "172.16.2.0/23"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_local_peering_gateway.export_DbsToWebLpg.id
    #route_type = <<Optional value not found in discovery>>
  }
  route_rules {
    description       = "route to auto_vcn"
    destination       = "172.16.4.0/24"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_local_peering_gateway.export_DbsToAutoLpg.id
    #route_type = <<Optional value not found in discovery>>
  }
  route_rules {
    description       = "Traffic to dr_vcn"
    destination       = "172.16.128.0/20"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_drg.export_dbs_drg.id
    #route_type = <<Optional value not found in discovery>>
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_nat_gateway.export_dbs_ngw.id
    #route_type = <<Optional value not found in discovery>>
  }
  route_rules {
    description       = "route to vpn_vcn"
    destination       = "172.16.7.0/24"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_local_peering_gateway.export_DbsToVpnLpg.id
    #route_type = <<Optional value not found in discovery>>
  }
  route_rules {
    description       = "route to vpn_vcn and intranet"
    destination       = "10.0.0.0/8"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_local_peering_gateway.export_DbsToVpnLpg.id
    #route_type = <<Optional value not found in discovery>>
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "172.16.5.0/24"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_local_peering_gateway.export_DbsToBasLpg.id
    #route_type = <<Optional value not found in discovery>>
  }
  vcn_id = oci_core_vcn.export_dbs_vcn.id
}

resource oci_core_default_route_table export_Default-Route-Table-for-dbs_vcn {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "edwinyoung@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2020-05-27T21:22:28.478Z"
  }
  display_name = "Default Route Table for dbs_vcn"
  freeform_tags = {
    "Environment" = "Production"
    "Platform"    = "Managed by Terraform"
  }
  manage_default_resource_id = oci_core_vcn.export_dbs_vcn.default_route_table_id
}

resource oci_core_security_list export_EM-DB-Subnet-Security-List---EMDBSubnet-172-16-0-0-24- {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/hankwojteczko@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2021-02-24T16:16:42.345Z"
  }
  display_name = "EM/DB Subnet Security List - EMDBSubnet (172.16.0.0/24)"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "all-iad-services-in-oracle-services-network"
    destination_type = "SERVICE_CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
    "Environment" = "Production"
    "Platform"    = "Managed by Terraform"
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "172.16.0.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "172.16.0.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  vcn_id = oci_core_vcn.export_dbs_vcn.id
}

resource oci_core_security_list export_dbs_sec {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/hankwojteczko@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2020-12-31T18:28:40.500Z"
  }
  display_name = "dbs_sec"
  egress_security_rules {
    description      = "required for OEM agents to ping OMS"
    destination      = "172.16.8.0/24"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "1"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "UDP to cloud tenant"
    destination      = "172.16.0.0/20"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "17"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "TCP to Internet"
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "Outbound to Printers on Port 9100"
    destination      = "10.0.0.0/8"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "false"
    tcp_options {
      max = "9100"
      min = "9100"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "UDP to Internet"
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "17"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
    "Environment" = "Production"
    "Platform"    = "Managed by Terraform"
  }
  ingress_security_rules {
    description = "SQLNET"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "172.16.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "1521"
      min = "1521"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "172.16.5.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "DR region ingress traffic"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "172.16.128.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  vcn_id = oci_core_vcn.export_dbs_vcn.id
}

resource oci_core_default_security_list export_Default-Security-List-for-dbs_vcn {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "edwinyoung@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2020-05-27T21:22:28.478Z"
  }
  display_name = "Default Security List for dbs_vcn"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "172.16.0.0/20"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "false"
    tcp_options {
      max = "65535"
      min = "1"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "172.16.0.0/20"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "1"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "false"
    tcp_options {
      max = "443"
      min = "443"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "172.16.0.0/20"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "17"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    udp_options {
      max = "65535"
      min = "1"
      #source_port_range = <<Optional value not found in discovery>>
    }
  }
  freeform_tags = {
    "Environment" = "Production"
    "Platform"    = "Managed by Terraform"
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "17"
    source      = "172.16.0.0/20"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    udp_options {
      max = "65535"
      min = "1"
      #source_port_range = <<Optional value not found in discovery>>
    }
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "1"
    source      = "172.16.0.0/20"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "172.16.0.0/20"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "65535"
      min = "1"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  manage_default_resource_id = oci_core_vcn.export_dbs_vcn.default_security_list_id
}

resource oci_core_instance export_kentemsp01_1 {
  agent_config {
    are_all_plugins_disabled = "false"
    is_management_disabled   = "false"
    is_monitoring_disabled   = "false"
    plugins_config {
      desired_state = "DISABLED"
      name          = "Vulnerability Scanning"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Oracle Java Management Service"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "OS Management Service Agent"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Management Agent"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Custom Logs Monitoring"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Compute Instance Run Command"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Compute Instance Monitoring"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Block Volume Management"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Bastion"
    }
  }
  #async = <<Optional value not found in discovery>>
  availability_config {
    is_live_migration_preferred = "false"
    recovery_action             = "RESTORE_INSTANCE"
  }
  availability_domain = var.availability_domain--clNq-US-ASHBURN-AD-1
  #capacity_reservation_id = <<Optional value not found in discovery>>
  compartment_id = var.compartment_ocid
  create_vnic_details {
    #assign_private_dns_record = <<Optional value not found in discovery>>
    assign_public_ip = "false"
    defined_tags = {
      "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/hankwojteczko@davidkentconsulting.com"
      "Oracle-Tags.CreatedOn" = "2022-12-01T18:00:37.054Z"
    }
    display_name = "kentemsp01"
    freeform_tags = {
    }
    hostname_label = "kentemsp01"
    nsg_ids = [
    ]
    private_ip             = "172.16.0.239"
    skip_source_dest_check = "false"
    subnet_id              = oci_core_subnet.export_dbs_sub.id
    #vlan_id = <<Optional value not found in discovery>>
  }
  #dedicated_vm_host_id = <<Optional value not found in discovery>>
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/hankwojteczko@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2022-12-01T18:00:36.891Z"
  }
  display_name = "kentemsp01"
  extended_metadata = {
  }
  fault_domain = var.fault_domain--FAULT-DOMAIN-3
  freeform_tags = {
    "Environment" = "Production"
    "Platform"    = "Managed by Terraform"
  }
  instance_options {
    are_legacy_imds_endpoints_disabled = "false"
  }
  #ipxe_script = <<Optional value not found in discovery>>
  #is_pv_encryption_in_transit_enabled = <<Optional value not found in discovery>>
  launch_options {
    boot_volume_type                    = "PARAVIRTUALIZED"
    firmware                            = "UEFI_64"
    is_consistent_volume_naming_enabled = "true"
    is_pv_encryption_in_transit_enabled = "true"
    network_type                        = "PARAVIRTUALIZED"
    remote_data_volume_type             = "PARAVIRTUALIZED"
  }
  metadata = {
    "ssh_authorized_keys" = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDnOulRB/oHiIR7uV4q+BVo8BDc5E7ixmcxvKwg9UyL+9YNT4lwYUd93k3LhP40LidpEEVL3TdkFizDNzkCsHxbDTp0jMv4w6+irWQuYfQjIdFkEyuAnrZV88H5/Uwlda6h9RZtgB7PDNrv9q3GTHs87W+p4bAlLCsT7BCvWh6BSXHD6y2mAfzr22yBtGojhq+sCL9L4397XhwEOiLNcSdWc/tP2vXW7HCokFXVaLXjbUyJTgAancag7vnLtyoyeFsfdF9mqOZnL3G3QIbkubMYX/wlDKx3QrZA4v/tBcAZBxREqEiJubUVav4TJFodXQJ3z4Nsqe6rb0/XIuPDlpjJ henrywojteczko@Henrys-MacBook-Pro-2.local"
  }
  #preserve_boot_volume = <<Optional value not found in discovery>>
  shape = "VM.Standard.E4.Flex"
  shape_config {
    baseline_ocpu_utilization = ""
    memory_in_gbs             = "8"
    nvmes                     = "0"
    ocpus                     = "1"
  }
  source_details {
    boot_volume_size_in_gbs = "100"
    boot_volume_vpus_per_gb = "10"
    #kms_key_id = <<Optional value not found in discovery>>
    source_id   = var.oci_core_instance--source_details-source_id--export_kentjsubt01_1
    source_type = "image"
  }
  state = "STOPPED"
}

resource oci_core_instance export_kentjsubp01_1 {
  agent_config {
    are_all_plugins_disabled = "false"
    is_management_disabled   = "false"
    is_monitoring_disabled   = "false"
    plugins_config {
      desired_state = "DISABLED"
      name          = "Vulnerability Scanning"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Oracle Java Management Service"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "OS Management Service Agent"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Management Agent"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Custom Logs Monitoring"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Compute Instance Run Command"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Compute Instance Monitoring"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Block Volume Management"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Bastion"
    }
  }
  #async = <<Optional value not found in discovery>>
  availability_config {
    is_live_migration_preferred = "false"
    recovery_action             = "RESTORE_INSTANCE"
  }
  availability_domain = var.availability_domain--clNq-US-ASHBURN-AD-2
  #capacity_reservation_id = <<Optional value not found in discovery>>
  compartment_id = var.compartment_ocid
  create_vnic_details {
    #assign_private_dns_record = <<Optional value not found in discovery>>
    assign_public_ip = "false"
    defined_tags = {
      "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/hankwojteczko@davidkentconsulting.com"
      "Oracle-Tags.CreatedOn" = "2022-12-01T17:59:49.899Z"
    }
    display_name = "kentjsubp01"
    freeform_tags = {
      "Environment" = "Production"
      "Platform"    = "Managed by Terraform"
    }
    hostname_label = "kentjsubp01"
    nsg_ids = [
    ]
    private_ip             = "172.16.0.50"
    skip_source_dest_check = "false"
    subnet_id              = oci_core_subnet.export_dbs_sub.id
    #vlan_id = <<Optional value not found in discovery>>
  }
  #dedicated_vm_host_id = <<Optional value not found in discovery>>
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/hankwojteczko@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2022-12-01T17:59:49.323Z"
  }
  display_name = "kentjsubp01"
  extended_metadata = {
  }
  fault_domain = var.fault_domain--FAULT-DOMAIN-3
  freeform_tags = {
    "Environment" = "Production"
    "Platform"    = "Managed by Terraform"
  }
  instance_options {
    are_legacy_imds_endpoints_disabled = "false"
  }
  #ipxe_script = <<Optional value not found in discovery>>
  #is_pv_encryption_in_transit_enabled = <<Optional value not found in discovery>>
  launch_options {
    boot_volume_type                    = "PARAVIRTUALIZED"
    firmware                            = "UEFI_64"
    is_consistent_volume_naming_enabled = "true"
    is_pv_encryption_in_transit_enabled = "false"
    network_type                        = "PARAVIRTUALIZED"
    remote_data_volume_type             = "PARAVIRTUALIZED"
  }
  metadata = {
    "ssh_authorized_keys" = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDnOulRB/oHiIR7uV4q+BVo8BDc5E7ixmcxvKwg9UyL+9YNT4lwYUd93k3LhP40LidpEEVL3TdkFizDNzkCsHxbDTp0jMv4w6+irWQuYfQjIdFkEyuAnrZV88H5/Uwlda6h9RZtgB7PDNrv9q3GTHs87W+p4bAlLCsT7BCvWh6BSXHD6y2mAfzr22yBtGojhq+sCL9L4397XhwEOiLNcSdWc/tP2vXW7HCokFXVaLXjbUyJTgAancag7vnLtyoyeFsfdF9mqOZnL3G3QIbkubMYX/wlDKx3QrZA4v/tBcAZBxREqEiJubUVav4TJFodXQJ3z4Nsqe6rb0/XIuPDlpjJ henrywojteczko@Henrys-MacBook-Pro-2.local"
  }
  #preserve_boot_volume = <<Optional value not found in discovery>>
  shape = "VM.Standard.E4.Flex"
  shape_config {
    baseline_ocpu_utilization = ""
    memory_in_gbs             = "8"
    nvmes                     = "0"
    ocpus                     = "1"
  }
  source_details {
    boot_volume_size_in_gbs = "100"
    boot_volume_vpus_per_gb = "10"
    #kms_key_id = <<Optional value not found in discovery>>
    source_id   = var.oci_core_instance--source_details-source_id--export_kentjsubt01_1
    source_type = "image"
  }
  state = "STOPPED"
}

resource oci_core_instance export_kentjsubt01_1 {
  agent_config {
    are_all_plugins_disabled = "false"
    is_management_disabled   = "false"
    is_monitoring_disabled   = "false"
    plugins_config {
      desired_state = "DISABLED"
      name          = "Vulnerability Scanning"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Oracle Java Management Service"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "OS Management Service Agent"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Management Agent"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Custom Logs Monitoring"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Compute Instance Run Command"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Compute Instance Monitoring"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Block Volume Management"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Bastion"
    }
  }
  #async = <<Optional value not found in discovery>>
  availability_config {
    is_live_migration_preferred = "false"
    recovery_action             = "RESTORE_INSTANCE"
  }
  availability_domain = var.availability_domain--clNq-US-ASHBURN-AD-3
  #capacity_reservation_id = <<Optional value not found in discovery>>
  compartment_id = var.compartment_ocid
  create_vnic_details {
    #assign_private_dns_record = <<Optional value not found in discovery>>
    assign_public_ip = "false"
    defined_tags = {
      "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/hankwojteczko@davidkentconsulting.com"
      "Oracle-Tags.CreatedOn" = "2022-12-01T17:59:04.322Z"
    }
    display_name = "kentjsubt01"
    freeform_tags = {
    }
    hostname_label = "kentjsubt01"
    nsg_ids = [
    ]
    private_ip             = "172.16.0.154"
    skip_source_dest_check = "false"
    subnet_id              = oci_core_subnet.export_dbs_sub.id
    #vlan_id = <<Optional value not found in discovery>>
  }
  #dedicated_vm_host_id = <<Optional value not found in discovery>>
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/hankwojteczko@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2022-12-01T17:59:04.173Z"
  }
  display_name = "kentjsubt01"
  extended_metadata = {
  }
  fault_domain = var.fault_domain--FAULT-DOMAIN-3
  freeform_tags = {
    "Environment" = "Production"
    "Platform"    = "Managed by Terraform"
  }
  instance_options {
    are_legacy_imds_endpoints_disabled = "false"
  }
  #ipxe_script = <<Optional value not found in discovery>>
  #is_pv_encryption_in_transit_enabled = <<Optional value not found in discovery>>
  launch_options {
    boot_volume_type                    = "PARAVIRTUALIZED"
    firmware                            = "UEFI_64"
    is_consistent_volume_naming_enabled = "true"
    is_pv_encryption_in_transit_enabled = "false"
    network_type                        = "PARAVIRTUALIZED"
    remote_data_volume_type             = "PARAVIRTUALIZED"
  }
  metadata = {
    "ssh_authorized_keys" = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDnOulRB/oHiIR7uV4q+BVo8BDc5E7ixmcxvKwg9UyL+9YNT4lwYUd93k3LhP40LidpEEVL3TdkFizDNzkCsHxbDTp0jMv4w6+irWQuYfQjIdFkEyuAnrZV88H5/Uwlda6h9RZtgB7PDNrv9q3GTHs87W+p4bAlLCsT7BCvWh6BSXHD6y2mAfzr22yBtGojhq+sCL9L4397XhwEOiLNcSdWc/tP2vXW7HCokFXVaLXjbUyJTgAancag7vnLtyoyeFsfdF9mqOZnL3G3QIbkubMYX/wlDKx3QrZA4v/tBcAZBxREqEiJubUVav4TJFodXQJ3z4Nsqe6rb0/XIuPDlpjJ henrywojteczko@Henrys-MacBook-Pro-2.local"
  }
  #preserve_boot_volume = <<Optional value not found in discovery>>
  shape = "VM.Standard.E4.Flex"
  shape_config {
    baseline_ocpu_utilization = ""
    memory_in_gbs             = "8"
    nvmes                     = "0"
    ocpus                     = "1"
  }
  source_details {
    boot_volume_size_in_gbs = "100"
    boot_volume_vpus_per_gb = "10"
    #kms_key_id = <<Optional value not found in discovery>>
    source_id   = var.oci_core_instance--source_details-source_id--export_kentjsubt01_1
    source_type = "image"
  }
  state = "STOPPED"
}

