## This configuration was generated by terraform-provider-oci

resource oci_database_pluggable_database export_pluggable_database_1 {
  container_database_id = "ocid1.database.oc1.iad.anuwcljsdugb54qasibn3jytneohlfsirgfeencr6y4glrloky36d3n7t4ja"
  defined_tags = {
  }
  freeform_tags = {
  }
  #pdb_admin_password = <<Optional value not found in discovery>>
  pdb_name = "KENTCATP01PDB"
  #should_pdb_admin_account_be_locked = <<Optional value not found in discovery>>
  #tde_wallet_password = <<Optional value not found in discovery>>
}

resource oci_database_pluggable_database export_pluggable_database_2 {
  container_database_id = "ocid1.database.oc1.iad.anuwcljtdugb54qazfxcmq2ghs2g26vipb27vqriddocsmxcxirjfwwnidba"
  defined_tags = {
  }
  freeform_tags = {
  }
  #pdb_admin_password = <<Optional value not found in discovery>>
  pdb_name = "KENTT01PDB"
  #should_pdb_admin_account_be_locked = <<Optional value not found in discovery>>
  #tde_wallet_password = <<Optional value not found in discovery>>
}

resource oci_database_pluggable_database export_pluggable_database_3 {
  container_database_id = "ocid1.database.oc1.iad.anuwcljrdugb54qatgztuaasnvn2lqt5rlwnpzwwakzzqsivi35mphjll7qq"
  defined_tags = {
  }
  freeform_tags = {
  }
  #pdb_admin_password = <<Optional value not found in discovery>>
  pdb_name = "KENTDBP01PDB"
  #should_pdb_admin_account_be_locked = <<Optional value not found in discovery>>
  #tde_wallet_password = <<Optional value not found in discovery>>
}

resource oci_database_db_system export_KENTCATP01CDB {
  availability_domain = var.availability_domain--clNq-US-ASHBURN-AD-1
  #backup_network_nsg_ids = <<Optional value not found in discovery>>
  #backup_subnet_id = <<Optional value not found in discovery>>
  #cluster_name = <<Optional value not found in discovery>>
  compartment_id = var.compartment_ocid
  cpu_core_count = "1"
  data_collection_options {
    is_diagnostics_events_enabled = "false"
    is_health_monitoring_enabled  = "false"
    is_incident_logs_enabled      = "false"
  }
  data_storage_percentage = "80"
  data_storage_size_in_gb = "256"
  database_edition        = "STANDARD_EDITION"
  db_home {
    #create_async = <<Optional value not found in discovery>>
    database {
      admin_password = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
      #backup_id = <<Optional value not found in discovery>>
      #backup_tde_password = <<Optional value not found in discovery>>
      character_set = "AL32UTF8"
      #database_id = <<Optional value not found in discovery>>
      #database_software_image_id = <<Optional value not found in discovery>>
      db_backup_config {
        auto_backup_enabled = "false"
        auto_backup_window  = ""
        #recovery_window_in_days = <<Optional value not found in discovery>>
      }
      #db_domain = <<Optional value not found in discovery>>
      db_name     = "CATP01"
      db_workload = "OLTP"
      defined_tags = {
        "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/hankwojteczko@davidkentconsulting.com"
        "Oracle-Tags.CreatedOn" = "2022-12-01T18:45:06.220Z"
      }
      freeform_tags = {
      }
      #kms_key_id = <<Optional value not found in discovery>>
      #kms_key_version_id = <<Optional value not found in discovery>>
      ncharacter_set = "AL16UTF16"
      pdb_name       = "KENTCATP01PDB"
      #tde_wallet_password = <<Optional value not found in discovery>>
      #time_stamp_for_point_in_time_recovery = <<Optional value not found in discovery>>
      #vault_id = <<Optional value not found in discovery>>
    }
    #database_software_image_id = <<Optional value not found in discovery>>
    db_version = "19.17.0.0"
    #defined_tags = <<Optional value not found in discovery>>
    display_name = "dbhome20221201184506"
    freeform_tags = {
    }
  }
  db_system_options {
    storage_management = "LVM"
  }
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/hankwojteczko@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2022-12-01T18:45:03.238Z"
  }
  disk_redundancy = "HIGH"
  display_name    = "KENTCATP01CDB"
  domain          = "dbssub.dbsvcn.oraclevcn.com"
  fault_domains = [
    "FAULT-DOMAIN-3",
  ]
  freeform_tags = {
  }
  hostname = "kentcatp01"
  #kms_key_id = <<Optional value not found in discovery>>
  #kms_key_version_id = <<Optional value not found in discovery>>
  license_model = "BRING_YOUR_OWN_LICENSE"
  #maintenance_window_details = <<Optional value not found in discovery>>
  node_count = "1"
  #nsg_ids = <<Optional value not found in discovery>>
  #private_ip = <<Optional value not found in discovery>>
  reco_storage_size_in_gb = "256"
  shape                   = "VM.Standard.E4.Flex"
  source                  = "NONE"
  #source_db_system_id = <<Optional value not found in discovery>>
  #sparse_diskgroup = <<Optional value not found in discovery>>
  ssh_public_keys = [
    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDnOulRB/oHiIR7uV4q+BVo8BDc5E7ixmcxvKwg9UyL+9YNT4lwYUd93k3LhP40LidpEEVL3TdkFizDNzkCsHxbDTp0jMv4w6+irWQuYfQjIdFkEyuAnrZV88H5/Uwlda6h9RZtgB7PDNrv9q3GTHs87W+p4bAlLCsT7BCvWh6BSXHD6y2mAfzr22yBtGojhq+sCL9L4397XhwEOiLNcSdWc/tP2vXW7HCokFXVaLXjbUyJTgAancag7vnLtyoyeFsfdF9mqOZnL3G3QIbkubMYX/wlDKx3QrZA4v/tBcAZBxREqEiJubUVav4TJFodXQJ3z4Nsqe6rb0/XIuPDlpjJ henrywojteczko@Henrys-MacBook-Pro-2.local",
  ]
  storage_volume_performance_mode = "HIGH_PERFORMANCE"
  subnet_id                       = oci_core_subnet.export_dbs_sub.id
  time_zone                       = "UTC"

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [db_home[0].database[0].admin_password]
  }
}

resource oci_database_db_system export_KENTDBT01CDB {
  availability_domain = var.availability_domain--clNq-US-ASHBURN-AD-2
  #backup_network_nsg_ids = <<Optional value not found in discovery>>
  #backup_subnet_id = <<Optional value not found in discovery>>
  #cluster_name = <<Optional value not found in discovery>>
  compartment_id = var.compartment_ocid
  cpu_core_count = "1"
  data_collection_options {
    is_diagnostics_events_enabled = "false"
    is_health_monitoring_enabled  = "false"
    is_incident_logs_enabled      = "false"
  }
  data_storage_percentage = "80"
  data_storage_size_in_gb = "256"
  database_edition        = "ENTERPRISE_EDITION"
  db_home {
    #create_async = <<Optional value not found in discovery>>
    database {
      admin_password = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
      #backup_id = <<Optional value not found in discovery>>
      #backup_tde_password = <<Optional value not found in discovery>>
      character_set = "AL32UTF8"
      #database_id = <<Optional value not found in discovery>>
      #database_software_image_id = <<Optional value not found in discovery>>
      db_backup_config {
        auto_backup_enabled = "false"
        auto_backup_window  = ""
        #recovery_window_in_days = <<Optional value not found in discovery>>
      }
      #db_domain = <<Optional value not found in discovery>>
      db_name     = "KENTT01"
      db_workload = "OLTP"
      defined_tags = {
        "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/hankwojteczko@davidkentconsulting.com"
        "Oracle-Tags.CreatedOn" = "2022-12-01T18:42:09.573Z"
      }
      freeform_tags = {
      }
      #kms_key_id = <<Optional value not found in discovery>>
      #kms_key_version_id = <<Optional value not found in discovery>>
      ncharacter_set = "AL16UTF16"
      pdb_name       = "KENTT01PDB"
      #tde_wallet_password = <<Optional value not found in discovery>>
      #time_stamp_for_point_in_time_recovery = <<Optional value not found in discovery>>
      #vault_id = <<Optional value not found in discovery>>
    }
    #database_software_image_id = <<Optional value not found in discovery>>
    db_version = "19.17.0.0"
    #defined_tags = <<Optional value not found in discovery>>
    display_name = "dbhome20221201184210"
    freeform_tags = {
    }
  }
  db_system_options {
    storage_management = "ASM"
  }
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/hankwojteczko@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2022-12-01T18:42:05.153Z"
  }
  disk_redundancy = "HIGH"
  display_name    = "KENTDBT01CDB"
  domain          = "dbssub.dbsvcn.oraclevcn.com"
  fault_domains = [
    "FAULT-DOMAIN-2",
  ]
  freeform_tags = {
  }
  hostname = "kentdbt01"
  #kms_key_id = <<Optional value not found in discovery>>
  #kms_key_version_id = <<Optional value not found in discovery>>
  license_model = "BRING_YOUR_OWN_LICENSE"
  #maintenance_window_details = <<Optional value not found in discovery>>
  node_count = "1"
  #nsg_ids = <<Optional value not found in discovery>>
  #private_ip = <<Optional value not found in discovery>>
  reco_storage_size_in_gb = "256"
  shape                   = "VM.Standard.E4.Flex"
  source                  = "NONE"
  #source_db_system_id = <<Optional value not found in discovery>>
  #sparse_diskgroup = <<Optional value not found in discovery>>
  ssh_public_keys = [
    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDnOulRB/oHiIR7uV4q+BVo8BDc5E7ixmcxvKwg9UyL+9YNT4lwYUd93k3LhP40LidpEEVL3TdkFizDNzkCsHxbDTp0jMv4w6+irWQuYfQjIdFkEyuAnrZV88H5/Uwlda6h9RZtgB7PDNrv9q3GTHs87W+p4bAlLCsT7BCvWh6BSXHD6y2mAfzr22yBtGojhq+sCL9L4397XhwEOiLNcSdWc/tP2vXW7HCokFXVaLXjbUyJTgAancag7vnLtyoyeFsfdF9mqOZnL3G3QIbkubMYX/wlDKx3QrZA4v/tBcAZBxREqEiJubUVav4TJFodXQJ3z4Nsqe6rb0/XIuPDlpjJ henrywojteczko@Henrys-MacBook-Pro-2.local",
  ]
  storage_volume_performance_mode = "BALANCED"
  subnet_id                       = oci_core_subnet.export_dbs_sub.id
  time_zone                       = "UTC"

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [db_home[0].database[0].admin_password]
  }
}

resource oci_database_db_system export_KENTCDBP01 {
  availability_domain = var.availability_domain--clNq-US-ASHBURN-AD-3
  #backup_network_nsg_ids = <<Optional value not found in discovery>>
  #backup_subnet_id = <<Optional value not found in discovery>>
  #cluster_name = <<Optional value not found in discovery>>
  compartment_id = var.compartment_ocid
  cpu_core_count = "1"
  data_collection_options {
    is_diagnostics_events_enabled = "false"
    is_health_monitoring_enabled  = "false"
    is_incident_logs_enabled      = "false"
  }
  data_storage_percentage = "80"
  data_storage_size_in_gb = "1024"
  database_edition        = "ENTERPRISE_EDITION"
  db_home {
    #create_async = <<Optional value not found in discovery>>
    database {
      admin_password = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
      #backup_id = <<Optional value not found in discovery>>
      #backup_tde_password = <<Optional value not found in discovery>>
      character_set = "AL32UTF8"
      #database_id = <<Optional value not found in discovery>>
      #database_software_image_id = <<Optional value not found in discovery>>
      db_backup_config {
        auto_backup_enabled = "false"
        auto_backup_window  = ""
        #recovery_window_in_days = <<Optional value not found in discovery>>
      }
      #db_domain = <<Optional value not found in discovery>>
      db_name     = "KENTP01"
      db_workload = "OLTP"
      defined_tags = {
        "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/hankwojteczko@davidkentconsulting.com"
        "Oracle-Tags.CreatedOn" = "2022-12-01T18:39:39.582Z"
      }
      freeform_tags = {
      }
      #kms_key_id = <<Optional value not found in discovery>>
      #kms_key_version_id = <<Optional value not found in discovery>>
      ncharacter_set = "AL16UTF16"
      pdb_name       = "KENTDBP01PDB"
      #tde_wallet_password = <<Optional value not found in discovery>>
      #time_stamp_for_point_in_time_recovery = <<Optional value not found in discovery>>
      #vault_id = <<Optional value not found in discovery>>
    }
    #database_software_image_id = <<Optional value not found in discovery>>
    db_version = "19.17.0.0"
    #defined_tags = <<Optional value not found in discovery>>
    display_name = "dbhome20221201183939"
    freeform_tags = {
    }
  }
  db_system_options {
    storage_management = "ASM"
  }
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/hankwojteczko@davidkentconsulting.com"
    "Oracle-Tags.CreatedOn" = "2022-12-01T18:39:38.220Z"
  }
  disk_redundancy = "HIGH"
  display_name    = "KENTCDBP01"
  domain          = "dbssub.dbsvcn.oraclevcn.com"
  fault_domains = [
    "FAULT-DOMAIN-2",
  ]
  freeform_tags = {
  }
  hostname = "kentdbp01"
  #kms_key_id = <<Optional value not found in discovery>>
  #kms_key_version_id = <<Optional value not found in discovery>>
  license_model = "BRING_YOUR_OWN_LICENSE"
  #maintenance_window_details = <<Optional value not found in discovery>>
  node_count = "1"
  #nsg_ids = <<Optional value not found in discovery>>
  #private_ip = <<Optional value not found in discovery>>
  reco_storage_size_in_gb = "512"
  shape                   = "VM.Standard.E4.Flex"
  source                  = "NONE"
  #source_db_system_id = <<Optional value not found in discovery>>
  #sparse_diskgroup = <<Optional value not found in discovery>>
  ssh_public_keys = [
    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDnOulRB/oHiIR7uV4q+BVo8BDc5E7ixmcxvKwg9UyL+9YNT4lwYUd93k3LhP40LidpEEVL3TdkFizDNzkCsHxbDTp0jMv4w6+irWQuYfQjIdFkEyuAnrZV88H5/Uwlda6h9RZtgB7PDNrv9q3GTHs87W+p4bAlLCsT7BCvWh6BSXHD6y2mAfzr22yBtGojhq+sCL9L4397XhwEOiLNcSdWc/tP2vXW7HCokFXVaLXjbUyJTgAancag7vnLtyoyeFsfdF9mqOZnL3G3QIbkubMYX/wlDKx3QrZA4v/tBcAZBxREqEiJubUVav4TJFodXQJ3z4Nsqe6rb0/XIuPDlpjJ henrywojteczko@Henrys-MacBook-Pro-2.local",
  ]
  storage_volume_performance_mode = "HIGH_PERFORMANCE"
  subnet_id                       = oci_core_subnet.export_dbs_sub.id
  time_zone                       = "UTC"

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [db_home[0].database[0].admin_password]
  }
}

