## This configuration was generated by terraform-provider-oci

resource oci_file_storage_export export_export_1 {
  export_options {
    access                         = "READ_WRITE"
    anonymous_gid                  = "65534"
    anonymous_uid                  = "65534"
    identity_squash                = "NONE"
    require_privileged_source_port = "false"
    source                         = "0.0.0.0/0"
  }
  export_set_id  = "ocid1.exportset.oc1.iad.aaaaaa4np2t6iz4tnfqwillqojxwiotjmfsc2ylefuyqaaaa"
  file_system_id = "ocid1.filesystem.oc1.iad.aaaaaaaaaabqehpjnfqwillqojxwiotjmfsc2ylefuyqaaaa"
  path           = "/kentnfst01"
}

resource oci_file_storage_export export_export_2 {
  export_options {
    access                         = "READ_WRITE"
    anonymous_gid                  = "65534"
    anonymous_uid                  = "65534"
    identity_squash                = "NONE"
    require_privileged_source_port = "false"
    source                         = "0.0.0.0/0"
  }
  export_set_id  = "ocid1.exportset.oc1.iad.aaaaacvippyvn6t5nfqwillqojxwiotjmfsc2ylefuzqaaaa"
  file_system_id = "ocid1.filesystem.oc1.iad.aaaaaaaaaabgqyzznfqwillqojxwiotjmfsc2ylefuzqaaaa"
  path           = "/kentnfsp01"
}
