## This configuration was generated by terraform-provider-oci

resource oci_file_storage_export export_export_1 {
  export_options {
    access                         = "READ_ONLY"
    anonymous_gid                  = "65534"
    anonymous_uid                  = "65534"
    identity_squash                = "ROOT"
    require_privileged_source_port = "true"
    source                         = "127.0.0.1/32"
  }
  export_options {
    access                         = "READ_WRITE"
    anonymous_gid                  = "65534"
    anonymous_uid                  = "65534"
    identity_squash                = "NONE"
    require_privileged_source_port = "true"
    source                         = "172.16.0.0/24"
  }
  export_set_id  = "ocid1.exportset.oc1.iad.aaaaaa4np2sz3pppnfqwillqojxwiotjmfsc2ylefuyqaaaa"
  file_system_id = "ocid1.filesystem.oc1.iad.aaaaaaaaaaa6rwrdnfqwillqojxwiotjmfsc2ylefuyqaaaa"
  path           = "/bin"
}

resource oci_file_storage_export export_export_2 {
  export_options {
    access                         = "READ_ONLY"
    anonymous_gid                  = "65534"
    anonymous_uid                  = "65534"
    identity_squash                = "ROOT"
    require_privileged_source_port = "false"
    source                         = "172.16.0.5"
  }
  export_set_id  = "ocid1.exportset.oc1.iad.aaaaaby27vfejihunfqwillqojxwiotjmfsc2ylefuzqaaaa"
  file_system_id = "ocid1.filesystem.oc1.iad.aaaaaaaaaaavmbbbnfqwillqojxwiotjmfsc2ylefuzqaaaa"
  path           = "/bin"
}

